# Generated by Django 5.0.6 on 2024-06-19 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persons',
            name='name',
            field=models.CharField(default='', max_length=50, unique=True, verbose_name='Имя'),
        ),
    ]
